#!/usr/bin/env python
# coding: utf-8

# # Week 1: Getting started Anaconda, Jupyter Notebook and Python
# Exercises to familiarise myself with Jupyter Notebook and its relationship to python

# #### Why did I choose this course?
# I joined this course because I want to learn more about AI applications in the humanities. I am really fasciniated by AI and how it is changing our world. I hope that this course will give me a deeper understanding of the functionality behind AI and its potential for creative industries. 

# #### My Experience with AI and Python
# - I have previously used Python as part of the DAVC course in my third year.
# - I work on a project for the German Red Cross exploring how AI and data science can create value for welfare services. We develop and execute pilot projects using AI applications.

# #### What I expect to learn from this course:
# - Learn about history of AI
# - Understand different categories of AI (Deep Learning, Machine Learning, Neural Networks)
# - Learn different application areas of AI and ways in which AI can be used
# - Expand my understanding of python and learn coding skills
# - Critically assess content generated by AI

# In[2]:


print ("hello, world!")


# In[3]:


message = "This is fun!"
print (message)


# In[5]:


print (message + message)


# In[6]:


print (message*3)


# In[7]:


print (message [0])


# In[11]:


print (message [1])


# In[12]:


print (message [2])


# In[13]:


print (message [3])


# In[15]:


content = "This is fun!"
print (content)


# In[2]:


from IPython.display import*


# In[3]:


YouTubeVideo("OhCzX0iLnOc")


# In[ ]:


import webbrowser
import requests

print("Shall we hunt down an old website?")
site = input("Type a website URL: ")
era = input("Type year, month, and date, e.g., 20150613: ")
url = "http://archive.org/wayback/available?url=%s&timestamp=%s" % (site, era)
response = requests.get(url)
data = response.json()
try:
    old_site = data["archived_snapshots"]["closest"]["url"]
    print("Found this copy: ", old_site)
    print("It should appear in your browser.")
    webbrowser.open(old_site)
except:
    print("Sorry, could not find the site.")


# # Lab Week 2/3 Multimedia Data on Python
# 

# In[1]:


from IPython.display import Image


# In[2]:


Image ("picture1.jpg")


# In[3]:


from IPython.display import Audio
Audio ("audio1.mid")


# In[3]:


from IPython.display import Audio
Audio ("GoldbergVariations_MehmetOkonsar-1of3_Var1to10(1).ogg")
# This file is licensed under the Creative Commons Attribution-Share Alike 3.0 Unported license.You are free:•	to share – to copy, distribute and transmit the work•	to remix – to adapt the workUnder the following conditions:•	attribution – You must give appropriate credit, provide a link to the license, and indicate if changes were made. You may do so in any reasonable manner, but not in any way that suggests the licensor endorses you or your use.•	share alike – If you remix, transform, or build upon the material, you must distribute your contributions under the same or compatible license as the original.The original ogg file was found at the url:https://en.wikipedia.org/wiki/File:GoldbergVariations_MehmetOkonsar-1of3_Var1to10.ogg


# #### Reflection on Audio Files
# While the audio player interface does load, both audio files cannot be played back. It makes sense that a midi file cannot be played since it does not contain any audio, but only information on pitch, rhythm and velocity. A midi file would need to be translated into audio with a sound generator found in a separate python library, such as "music21". However, the audio player should be able to correctly play the Ogg Vorbis file. A quick Google search suggests that this might be due to an error with the server hosting the jupyter notebook which leads to a misinterpretation of the .ogg MIMEtype. Other Formats such as WAV or MP3 are said to be more compatible.
# 
# Questions to the teacher: Why do my audio files not run?
# My Audiofile did not download as "audi2" but as Goldbergvarations... is that okay? Is the way I commented the code okay (siehe Goldberg Variations)

# ## Task 3.2 Representing images as numerical data

# In[19]:


from matplotlib import pyplot
test_picture = pyplot.imread ("picture1.jpg")
print ("Numpy array of the image is:", test_picture)
pyplot.imshow(test_picture)


# In[10]:


test_picture_filtered = 2*test_picture/3
pyplot.imshow(test_picture_filtered)


# In[17]:


test_picture_silly = 2*test_picture/85
pyplot.imshow(test_picture_silly)


# #### Reflection
# If we double the values in the array, the majority of RGB values will be so high that they exceed the maximum of 255. Therefore, we can expect the majority of the image to appear white (white = RGB(255,255,255)). In the first test picture, we divide the values by three, leaving most pixels still at very high RGB values. Only the darkest spots of the image remain visible, creating a faint outline of the hedgehog.
# 
# Dividing the values by 85, the RGB values become smaller and more of the hedgehog becomes visible again. The manipulation of RGB values distorts the colours and creates an unnatural appearance.

# ## Task 3.3 Exploring scikit-learn

# In[4]:


from sklearn import datasets
dir(datasets)


# ## My Datasets
# I chose the datasets load_breast_cancer , load_wine and load_sample_images. I chose the first data set since I am interested in exploring health data. I chose the second dataset since it is the one used in the lab book and I like being able to verify my results against the results in the lab book especially since I am not able to parttake in the labs and talk to my peers. I chose the last dataset since I am hoping that this contains some image data and I would be interested in working with some less traditional data sources.

# In[11]:


breastcancer_data = datasets.load_breast_cancer()


# In[12]:


print (breastcancer_data.DESCR)


# In[5]:


images_data = datasets.load_sample_images()
print (images_data.DESCR)


# In[15]:


wine_data = datasets.load_wine()
print (wine_data.DESCR)


# In[9]:


breastcancer_data.feature_names


# In[10]:


breastcancer_data.target_names


# In[17]:


wine_data.target_names


# In[18]:


wine_data.feature_names


# In[8]:


images_data.feature_names


# In[9]:


images_data.target_names


# In[7]:


print(images_data)


# In[17]:


print(len(breastcancer_data.feature_names))
print(len(wine_data.feature_names))


# #### Reflection
# 
# When trying to retrieve the feature and target names from the image dataset the notebook was throwing multiple errors. I then proceeded to print the dataset to have a closer look at its structure and hopefully get to the root cause of the issues. Upon closer examinations it seems as if the dataset does not have attributes called feature or target names, as it only consists of RGB Value arrays, filenames and a description. 
# 
# The wine dataset has 13 features and the breastcancer dataset has 30 features. Judging from the target names, it appears as if the wine dataset is aiming to classify wine into three categories based on the featuers.
# 

# # 3.4 Data Exploration using Pandas

# In[19]:


from sklearn import datasets
import pandas 
wine_data = datasets.load_wine()
wine_dataframe = pandas.DataFrame(data=wine_data['data'], columns = wine_data['feature_names'])


# In[20]:


wine_dataframe.head()


# In[21]:


wine_dataframe.describe()


# #### Reflection
# 
# The dataframe.head() function seems to return and visualize the first five rows of the dataset, wherease the dataframe.describe() function returns a set of the most common statistical descriptors of the dataset. 
# 

# ### STILL TO DO task 3.5 thinking about bias in data 
# How would i explore my datasets to assess bias? what would I look for?
# 
# - I would do simple exploratory data analysis such as simple visulisations to understand the data and see if there are any imbalances or outliers that come up, then I would further investigate these points
# - I would look at the data collection processes and question how concepts were operationalized, what would different apporaches to operationalizing this concept be and how might they alter the data? Who is represented in the data and why? For example, is there mainly men in this dataset because they currently dominate this field?
# - If I work with inidividual data I would check that no demographic group is over or underrepresented --> here I would also check for correlations with other variables e.g. are all women associated with lower paying jobs?
# - I would look at who or what collected the data. Is it only men? Have they paid special attention to bias and actively tried to counteract it)
# - I would check for class imbalances (when one class has more/less instances than the other classes), why did they occur?
# - I would test the data on a model and critical question the outcome, I would try and then 

# In[ ]:




